# Generated by Django 5.2.3 on 2025-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deneyim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozisyon', models.CharField(max_length=100)),
                ('sirket', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('baslangic', models.DateField()),
                ('bitis', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yetenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
    ]
