# Generated by Django 5.2.3 on 2025-06-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deneyim',
            name='saim',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
