# Generated by Django 5.2.3 on 2025-06-28 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_deneyim_saim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True)),
                ('ad', models.CharField(max_length=200)),
                ('tur', models.CharField(choices=[('aktif', 'Aktif'), ('pasif', 'Pasif'), ('gelir', 'Gelir'), ('gider', 'Gider'), ('nazim', 'Nazım')], max_length=10)),
                ('ust_hesap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.hesap')),
            ],
            options={
                'verbose_name': 'Muhasebe Hesabı',
                'verbose_name_plural': 'Muhasebe Hesapları',
            },
        ),
    ]
