# Generated by Django 5.2.3 on 2025-06-28 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_hesap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('aciklama', models.CharField(max_length=255)),
                ('belge_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FisHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(blank=True, max_length=255)),
                ('borc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alacak', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='cv.fis')),
                ('hesap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.hesap')),
            ],
        ),
    ]
